name: 'Handle the results of TestNG'
description: 'Read the XML results from TestNG, set some informational statuses and archive the results.'
author: 'UWHealth'
inputs:
  milliseconds:
    description: 'milliseconds to wait'
    default: '1000'
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
